# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm:\PhamHoangPhuong_2280602527\lab3\ui\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(36, 90, 61, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txtinfo = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinfo.setGeometry(QtCore.QRect(140, 90, 431, 71))
        self.txtinfo.setObjectName("txtinfo")
        self.txtsign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsign.setGeometry(QtCore.QRect(140, 200, 431, 71))
        self.txtsign.setObjectName("txtsign")
        self.btngenkey = QtWidgets.QPushButton(self.centralwidget)
        self.btngenkey.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.btngenkey.setObjectName("btngenkey")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(140, 290, 75, 23))
        self.btnsign.setObjectName("btnsign")
        self.btnverify = QtWidgets.QPushButton(self.centralwidget)
        self.btnverify.setGeometry(QtCore.QRect(490, 300, 75, 23))
        self.btnverify.setObjectName("btnverify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC_CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Infomation"))
        self.label_3.setText(_translate("MainWindow", "Signature"))
        self.btngenkey.setText(_translate("MainWindow", "GenKey"))
        self.btnsign.setText(_translate("MainWindow", "Sign"))
        self.btnverify.setText(_translate("MainWindow", "Verify"))
